f.soto.ceeavj@gmail.com

USE [master]
GO

/****** Object:  Database [WebAgenda]    Script Date: 01/02/2024 12:54:41 p. m. ******/
CREATE DATABASE [WebAgenda]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebAgenda', FILENAME = N'D:\04_SQL_Data\DBUser\WebAgenda.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebAgenda_log', FILENAME = N'D:\04_SQL_Data\DBUserLog\WebAgenda_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebAgenda].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebAgenda] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebAgenda] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebAgenda] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebAgenda] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebAgenda] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebAgenda] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebAgenda] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebAgenda] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebAgenda] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebAgenda] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebAgenda] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebAgenda] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebAgenda] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebAgenda] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebAgenda] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebAgenda] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebAgenda] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebAgenda] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebAgenda] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebAgenda] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebAgenda] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebAgenda] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebAgenda] SET RECOVERY FULL 
GO

ALTER DATABASE [WebAgenda] SET  MULTI_USER 
GO

ALTER DATABASE [WebAgenda] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebAgenda] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebAgenda] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebAgenda] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebAgenda] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebAgenda] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WebAgenda] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WebAgenda] SET  READ_WRITE 
GO


